// 日程事件(向前看):季度交割可确定性生成；宏观事件只能接纳官方日历的精确时间。
// 禁止用“首个周五/近似 UTC”猜非农，否则会把 Agent 引向错误的事件避险。
import test from "node:test";
import assert from "node:assert/strict";
import { ensureScheduledEvents, createScheduledEvent, upcomingScheduledEvents } from "../server/scheduledEvents.mjs";

const minimalDb = () => ({ events: [], auditLogs: [], meta: {}, user: { name: "test" } });

test("生成的日程事件全部落在周五(UTC)", () => {
  const db = minimalDb();
  ensureScheduledEvents(db);
  const sched = db.events.filter((e) => e.scheduled);
  assert.ok(sched.length > 0, "应生成若干日程事件");
  const notFriday = sched.filter((e) => new Date(e.due).getUTCDay() !== 5);
  assert.equal(notFriday.length, 0, "非农/季度交割都应在周五");
});

test("不再生成近似非农；官方 minute 精度宏观事件才进入高影响风险链", () => {
  const db = minimalDb();
  ensureScheduledEvents(db);
  assert.equal(db.events.some((e) => String(e.scheduledKey || "").startsWith("sched_nfp_")), false);
  db.marketCalendarEvents = [{
    id: "bls_nfp_exact", sourceName: "BLS", sourceUrl: "https://www.bls.gov/example",
    title: "Employment Situation", due: new Date(Date.now() + 86_400_000).toISOString(),
    timePrecision: "minute", importance: "high"
  }];
  ensureScheduledEvents(db);
  const nfp = db.events.find((e) => e.scheduledKey === "official_bls_nfp_exact");
  const exp = db.events.find((e) => /季度交割/.test(e.shortTitle || ""));
  assert.ok(nfp && nfp.impact >= 70 && nfp.category === "宏观");
  assert.equal(nfp.timePrecision, "minute");
  assert.ok(exp && exp.category === "衍生品");
});

test("季度交割只在季末月(3/6/9/12)", () => {
  const db = minimalDb();
  ensureScheduledEvents(db);
  const expiries = db.events.filter((e) => /季度交割/.test(e.shortTitle || ""));
  for (const e of expiries) {
    const m = new Date(e.due).getUTCMonth(); // 0基:2/5/8/11
    assert.ok([2, 5, 8, 11].includes(m), `交割月应为季末月,实际 ${m + 1} 月`);
  }
});

test("幂等:重复调用不产生重复事件", () => {
  const db = minimalDb();
  const first = ensureScheduledEvents(db).added;
  const second = ensureScheduledEvents(db).added;
  assert.ok(first > 0);
  assert.equal(second, 0, "第二次不应新增");
});

test("手动录入:拒绝空标题与非法日期", () => {
  const db = minimalDb();
  assert.ok(createScheduledEvent(db, { title: "", due: "2026-09-17T18:00:00Z" }).error);
  assert.ok(createScheduledEvent(db, { title: "FOMC", due: "not-a-date" }).error);
  assert.ok(createScheduledEvent(db, { title: "FOMC" }).error); // 缺日期
});

test("手动录入:合法则入库,impact 夹在 0–100", () => {
  const db = minimalDb();
  const r = createScheduledEvent(db, { title: "FOMC 议息", due: "2026-09-17T18:00:00Z", category: "宏观", impact: 999 });
  assert.equal(r.ok, true);
  assert.equal(r.event.impact, 100); // 夹取
  assert.equal(r.event.scheduled, true);
  assert.equal(r.event.autoGenerated, false);
});

test("upcomingScheduledEvents:只返回未来窗口内、按时间升序", () => {
  const db = minimalDb();
  const now = Date.now();
  db.events = [
    { id: "a", due: new Date(now - 3600000).toISOString() },      // 过去 → 排除
    { id: "b", due: new Date(now + 2 * 3600000).toISOString() },  // 未来 2h
    { id: "c", due: new Date(now + 1 * 3600000).toISOString() },  // 未来 1h
    { id: "d", due: new Date(now + 999 * 3600000).toISOString() } // 超窗(168h)→ 排除
  ];
  const up = upcomingScheduledEvents(db, 168);
  assert.deepEqual(up.map((e) => e.id), ["c", "b"]); // 升序 + 过滤
});
