const ownership = (domainId, workspaceId) => Object.freeze({ domainId, workspaceId });

export const KORDYN_V2_CAPABILITY_OWNERSHIP = Object.freeze({
  "ai.dialog": ownership("ai", "dialog"),
  "ai.autonomous-patrol": ownership("ai", "missions"),
  "ai.intelligence": ownership("ai", "intelligence"),
  "ai.watch": ownership("ai", "watch"),
  "ai.events": ownership("ai", "events"),
  "ai.poster-current": ownership("ai", "missions"),
  "ai.poster-translate": ownership("ai", "missions"),
  "ai.poster-png": ownership("ai", "missions"),

  "live.overview": ownership("account", "account"),
  "live.market": ownership("account", "market"),
  "live.account": ownership("account", "account"),
  "live.positions": ownership("account", "positions"),
  "live.execution": ownership("account", "plans"),
  "live.orders": ownership("account", "orders"),
  "live.fills": ownership("account", "fills"),
  "live.protection": ownership("account", "positions"),
  "live.reconcile-status": ownership("account", "account"),
  "live.review-status": ownership("account", "fills"),
  "live.closed-trade-poster": ownership("account", "fills"),

  "lab.research-map": ownership("assets", "relationships"),
  "lab.knowledge-import": ownership("assets", "knowledge"),
  "lab.knowledge-evidence": ownership("assets", "knowledge"),
  "lab.knowledge-graph": ownership("assets", "knowledge"),
  "lab.knowledge-artifacts": ownership("assets", "knowledge"),
  "lab.knowledge-workflows": ownership("assets", "knowledge"),
  "lab.strategy-core": ownership("assets", "strategies"),
  "lab.strategy-studio": ownership("assets", "strategies"),
  "lab.strategy-knowledge": ownership("assets", "strategies"),
  "lab.strategy-imported": ownership("assets", "strategies"),
  "lab.strategy-adaptive": ownership("assets", "strategies"),
  "lab.capability-native": ownership("assets", "capabilities"),
  "lab.capability-workflow": ownership("assets", "capabilities"),
  "lab.capability-imported-skill": ownership("assets", "capabilities"),
  "lab.capability-mcp": ownership("assets", "capabilities"),
  "lab.capability-connectors": ownership("assets", "capabilities"),
  "lab.trade-review": ownership("assets", "reviews"),
  "lab.owner-review": ownership("assets", "reviews"),

  "control.risk-posture": ownership("governance", "overview"),
  "control.operating-mode": ownership("governance", "overview"),
  "control.mandate-context": ownership("governance", "overview"),
  "control.rule-monitor": ownership("governance", "overview"),
  "control.event-risk": ownership("governance", "event-inputs"),
  "control.permission-boundaries": ownership("governance", "overview"),
  "operations.runtime-health": ownership("governance", "overview"),
  "operations.tasks": ownership("governance", "runs"),
  "operations.task-runs": ownership("governance", "runs"),
  "operations.event-input-health": ownership("governance", "event-inputs"),
  "operations.notifications": ownership("governance", "notifications"),
  "operations.audit": ownership("governance", "audit"),
  "operations.reconcile": ownership("governance", "recovery"),
  "operations.recovery": ownership("governance", "recovery"),

  "configuration.operating-mode": ownership("governance", "configuration"),
  "configuration.mandate": ownership("governance", "configuration"),
  "configuration.risk-rules": ownership("governance", "configuration"),
  "configuration.environment": ownership("governance", "configuration"),
  "configuration.network": ownership("governance", "configuration"),
  "configuration.backup": ownership("governance", "configuration"),
  "configuration.security": ownership("governance", "configuration"),
  "configuration.exchange": ownership("governance", "configuration"),
  "configuration.event-sources": ownership("governance", "configuration"),
  "configuration.notifications": ownership("governance", "configuration"),
  "configuration.models": ownership("governance", "configuration"),
  "configuration.agents": ownership("governance", "configuration"),
  "configuration.users": ownership("governance", "configuration"),
  "configuration.subscriptions": ownership("governance", "configuration"),
  "configuration.account-profile": ownership("governance", "configuration")
});

export function domainForCapability(id) {
  return Object.hasOwn(KORDYN_V2_CAPABILITY_OWNERSHIP, id)
    ? KORDYN_V2_CAPABILITY_OWNERSHIP[id]
    : null;
}
