import { AlertOctagon, ArrowRight, RefreshCw, RotateCcw } from "lucide-react";

export function MobileRecoveryScreen({ model = {}, actions, actionsDisabled = false, onSelect = () => {} }) {
  const recovery = model.operations?.recovery || {};
  const report = recovery.latestReconciliation;
  const recoveryId = report?.id || "recovery-current";
  const permissions = model.permissions || {};
  return <section className="kordynV2GovernanceMobile" data-kordyn-v2-governance-mobile="recovery"><header><h2>恢复</h2><p>对账、调度与风险事件</p></header><button className="kordynV2MobileRecoveryTruth" type="button" data-kordyn-v2-object-type="Recovery" data-kordyn-v2-object-id={recoveryId} onClick={() => onSelect({ id: recoveryId, type: "Recovery", workspaceId: "governance" })}><span><strong>最新权威对账</strong><small>{report?.createdAt || "尚未运行"}</small></span><em>{report?.status || "Unavailable"}</em><span>{recovery.differences?.length || 0} 项差异 · {recovery.unknownOrders?.length || 0} 未知执行</span><ArrowRight size={17} /></button><button className="kordynV2MobilePrimary" type="button" disabled={actionsDisabled || permissions.reconcile !== true} onClick={() => actions?.reconcile?.()}><RefreshCw size={18} />运行权威对账</button><button className="kordynV2MobileObjectAction" type="button" disabled={actionsDisabled || permissions.writeTask !== true || !recovery.needsSchedulerRecovery} onClick={() => actions?.recoverScheduler?.()}><RotateCcw size={18} />恢复任务调度</button><section className="kordynV2MobileAttention"><header><span><strong>开放风险事件</strong><small>{recovery.openIncidents?.length || 0} 项</small></span></header>{(recovery.openIncidents || []).map((row) => <article className="kordynV2MobileRecoveryIncident" key={row.id}><button type="button" data-kordyn-v2-object-type="Risk incident" data-kordyn-v2-object-id={row.id} onClick={() => onSelect({ id: row.id, type: "Risk incident", workspaceId: "governance" })}><AlertOctagon size={19} /><span><strong>{row.title || row.source || row.id}</strong><small>{row.status || "open"}</small></span><ArrowRight size={17} /></button><button type="button" disabled={actionsDisabled || permissions.writeRisk !== true} onClick={() => actions?.resolveRiskIncident?.(row.id)}>标记已处理</button></article>)}</section></section>;
}
