import { ArrowRight, CirclePause, CirclePlay } from "lucide-react";

export function MobileTaskRunScreen({ model = {}, actions, actionsDisabled = false, onSelect = () => {}, embedded = false }) {
  const tasks = model.operations?.tasks?.items || [];
  const runs = model.operations?.tasks?.recentRuns || [];
  const blocked = actionsDisabled || model.permissions?.writeTask !== true;
  const body = <><section className="kordynV2MobileGovernanceList"><header><span><strong>Task Registry</strong><small>{tasks.length} 项</small></span></header>{tasks.map((task) => <article className="kordynV2MobileTask" key={task.id}><button type="button" data-kordyn-v2-object-type="Task" data-kordyn-v2-object-id={task.id} onClick={() => onSelect({ id: task.id, type: "Task", workspaceId: "governance" })}><i data-tone={task.runtime?.tone} /><span><strong>{task.name || task.handler}</strong><small>{task.systemManaged ? "系统托管 · System-managed" : "用户任务"}</small></span><em>{task.runtime?.code || "unknown"}</em><ArrowRight size={16} /></button><div><button type="button" disabled={blocked || task.enabled === false} onClick={() => actions?.runTask?.(task.id)}><CirclePlay size={16} />运行</button><button type="button" disabled={blocked} onClick={() => task.enabled === false ? actions?.resumeTask?.(task.id) : actions?.pauseTask?.(task.id)}><CirclePause size={16} />{task.enabled === false ? "恢复" : "暂停"}</button></div></article>)}</section><section className="kordynV2MobileGovernanceList"><header><span><strong>Agent / System Run</strong><small>{runs.length} 项</small></span></header>{runs.map((run) => <button type="button" key={run.id} data-kordyn-v2-object-type="Agent run" data-kordyn-v2-object-id={run.id} onClick={() => onSelect({ id: run.id, type: "Agent run", workspaceId: "governance" })}><i data-tone={/fail|error/i.test(String(run.status)) ? "critical" : /partial|pending/i.test(String(run.status)) ? "warning" : "healthy"} /><span><strong>{run.taskName || run.name || run.id}</strong><small>{run.createdAt || run.finishedAt || "时间不可用"}</small></span><em>{run.status || "unknown"}</em><ArrowRight size={16} /></button>)}</section></>;
  if (embedded) return <div className="kordynV2MobileTaskRunEmbedded">{body}</div>;
  return <section className="kordynV2GovernanceMobile" data-kordyn-v2-governance-mobile="runs"><header><h2>任务与运行</h2><p>任务所有权与真实结果分开显示</p></header>{body}</section>;
}
