// 日程事件(向前看):与"已发生的 RSS 新闻"(向后看)互补。带【未来 due】的已排期事件,
// 落到事件日历的未来日期 + 喂 S7 事件透镜 + 事件静默窗口。
//
// 诚实原则:只【自动生成确定性可算】的事件(规则驱动,不编造具体日期):
//   · 季度交割:季末月(3/6/9/12)的最后一个周五(多数永续/交割合约季度结算)
// 宏观发布时间不再用“首个周五/约 13:30 UTC”等规则猜测；只接纳官方日历且带精确时间的事件。
// 官方只给日期、不提供时刻的 FOMC 事件只进入情报日历，不进入分钟级静默窗口。
import { id, nowIso, appendAudit } from "./store.mjs";
import { createNotification } from "./notificationStore.mjs";

const DAY = 86400000;

// 宏观/交割是全市场事件(非农、季度交割冲击所有主流永续)。自动生成的日程事件此前不带 relatedSymbols,
// 导致风控事件闸(需 relatedSymbols 匹配)、按标的的信息面简报与动态规则都连不上它们。这里默认标注主流币,
// 使这些市场级事件对常见授权标的真正生效。可用 MACRO_EVENT_SYMBOLS 环境变量覆盖。
const MACRO_EVENT_SYMBOLS = (process.env.MACRO_EVENT_SYMBOLS || "BTC/USDT,ETH/USDT,SOL/USDT,BNB/USDT,XRP/USDT,DOGE/USDT,ADA/USDT,SUI/USDT,LINK/USDT,AVAX/USDT")
  .split(",").map((s) => s.trim().toUpperCase()).filter(Boolean);

// 某年某月(0基)的最后一个周五(UTC)
function lastFridayUTC(year, month) {
  const d = new Date(Date.UTC(year, month + 1, 0)); // 该月最后一天
  const diff = (d.getUTCDay() - 5 + 7) % 7;          // 周五=5
  d.setUTCDate(d.getUTCDate() - diff);
  return d;
}
// 生成从 now 起未来窗口内的确定性日程事件(不落库,纯计算)。
function generateDeterministic(now = Date.now()) {
  const out = [];
  const base = new Date(now);
  const y0 = base.getUTCFullYear();
  const m0 = base.getUTCMonth();
  // 季度交割:向后 5 个季度扫季末月
  for (let q = 0; q < 6; q += 1) {
    const y = y0, m = 2 + q * 3; // Mar(2)/Jun(5)/Sep(8)/Dec(11)/next Mar...
    const yy = y + Math.floor(m / 12);
    const mm = m % 12;
    if (![2, 5, 8, 11].includes(mm)) continue;
    const d = lastFridayUTC(yy, mm);
    d.setUTCHours(8, 0, 0, 0); // 季度结算约 08:00 UTC
    if (d.getTime() > now - DAY) {
      out.push({ key: `sched_expiry_${yy}${String(mm + 1).padStart(2, "0")}`, title: `${yy}年${mm + 1}月季度合约交割`, shortTitle: "季度交割", due: d.toISOString(), category: "衍生品", impact: 55, note: "季度交割前后波动与基差收敛,注意持仓与保证金" });
    }
  }
  return out;
}

// 幂等落库:补齐缺失的确定性日程事件,清掉已过期>2天的自动日程(避免日历堆积)。
export function ensureScheduledEvents(db, actor = "ScheduledEvents") {
  db.events ||= [];
  const now = Date.now();
  // 删除旧版本按规则猜出的 NFP 时刻，避免近似 UTC 继续驱动实盘静默窗口。
  db.events = db.events.filter((e) => !String(e.scheduledKey || "").startsWith("sched_nfp_"));
  // 清过期的自动日程
  db.events = db.events.filter((e) => !(e.scheduled && e.autoGenerated && new Date(e.due || 0).getTime() < now - 2 * DAY));
  // 回填:存量自动事件此前没带 relatedSymbols/marketWide,幂等跳过会永远缺失 → 主动补上,使事件闸立即对存量生效。
  let patched = 0;
  for (const e of db.events) {
    if (e.scheduled && e.autoGenerated && (!Array.isArray(e.relatedSymbols) || !e.relatedSymbols.length)) {
      e.relatedSymbols = MACRO_EVENT_SYMBOLS.slice();
      e.marketWide = true;
      patched += 1;
    }
  }
  let added = 0;
  for (const g of generateDeterministic(now)) {
    if (db.events.some((e) => e.scheduledKey === g.key)) continue;
    db.events.unshift({
      id: id("event"), scheduled: true, autoGenerated: true, scheduledKey: g.key,
      title: g.title, shortTitle: g.shortTitle, due: g.due, startAt: g.due,
      category: g.category, impact: g.impact, impactLabel: g.impact >= 70 ? "高影响" : g.impact >= 50 ? "中影响" : "低影响",
      marketWide: true, relatedSymbols: MACRO_EVENT_SYMBOLS.slice(),
      source: "日程(系统)", description: g.note, createdAt: nowIso()
    });
    added += 1;
  }
  // 只有官方源给出 minute 精度时才写入事件风险链；date-only 事件保留在 marketCalendarEvents 供分析关注。
  for (const official of db.marketCalendarEvents || []) {
    if (official.timePrecision !== "minute" || official.importance !== "high") continue;
    const due = new Date(official.due).getTime();
    if (!Number.isFinite(due) || due < now - DAY) continue;
    const key = `official_${official.id}`;
    const existing = db.events.find((event) => event.scheduledKey === key);
    if (existing) {
      const before = JSON.stringify({
        due: existing.due, startAt: existing.startAt, sourceLink: existing.sourceLink,
        timePrecision: existing.timePrecision, impact: existing.impact, impactLabel: existing.impactLabel,
        sourceId: existing.sourceId, sourceName: existing.sourceName, verified: existing.verified,
        autoTradingEligible: existing.autoTradingEligible, provenance: existing.provenance
      });
      existing.due = official.due;
      existing.startAt = official.due;
      existing.sourceLink = official.sourceUrl;
      existing.timePrecision = official.timePrecision;
      existing.impact = Math.max(90, Number(existing.impact) || 0);
      existing.impactLabel = "高影响";
      existing.sourceId = official.sourceId;
      existing.sourceName = official.sourceName;
      existing.verified = true;
      existing.autoTradingEligible = true;
      existing.provenance = { ...(existing.provenance || {}), trustTier: "verified_official_calendar", verifiedOrigin: true };
      const after = JSON.stringify({
        due: existing.due, startAt: existing.startAt, sourceLink: existing.sourceLink,
        timePrecision: existing.timePrecision, impact: existing.impact, impactLabel: existing.impactLabel,
        sourceId: existing.sourceId, sourceName: existing.sourceName, verified: existing.verified,
        autoTradingEligible: existing.autoTradingEligible, provenance: existing.provenance
      });
      if (before !== after) patched += 1;
      continue;
    }
    db.events.unshift({
      id: id("event"), scheduled: true, autoGenerated: true, scheduledKey: key,
      title: official.title, shortTitle: official.title.slice(0, 16), due: official.due, startAt: official.due,
      category: "宏观", impact: 90, impactLabel: "高影响", marketWide: true,
      relatedSymbols: MACRO_EVENT_SYMBOLS.slice(), source: `官方日历(${official.sourceName})`,
      sourceId: official.sourceId, sourceName: official.sourceName,
      sourceLink: official.sourceUrl, timePrecision: official.timePrecision, verified: true, autoTradingEligible: true,
      provenance: { trustTier: "verified_official_calendar", verifiedOrigin: true },
      description: "官方发布日历确认的精确事件时间", createdAt: nowIso()
    });
    added += 1;
  }
  return { added, patched };
}

// 手动添加一条日程事件(用户录入 FOMC/CPI/解锁 等已知日期)。
export function createScheduledEvent(db, payload = {}, actor = "User") {
  db.events ||= [];
  const due = payload.due ? new Date(payload.due) : null;
  if (!due || Number.isNaN(due.getTime())) return { error: "请提供有效日期时间" };
  const forbidden = Object.keys(payload).filter((key) => !["title", "due", "impact", "category", "note", "relatedSymbols", "timePrecision"].includes(key));
  if (forbidden.length) return { error: `不允许的日程字段：${forbidden.join("、")}` };
  const title = String(payload.title || "").trim();
  if (!title || title.length > 160) return { error: "事件名称必须为 1–160 个字符" };
  const impact = Math.max(0, Math.min(100, Number(payload.impact) || 60));
  const event = {
    id: id("event"), scheduled: true, autoGenerated: false, kind: "unverified_manual",
    title, shortTitle: (payload.shortTitle || title).slice(0, 16),
    due: due.toISOString(), startAt: due.toISOString(),
    category: String(payload.category || "宏观").slice(0, 12),
    impact, impactLabel: impact >= 70 ? "高影响" : impact >= 50 ? "中影响" : "低影响",
    source: "日程(手动)", description: String(payload.note || "").slice(0, 200),
    // 用户明确录入了日期时间，事件统计/分钟级静默窗口才可把它当精确时点使用。
    timePrecision: "minute",
    relatedSymbols: Array.isArray(payload.relatedSymbols)
      ? [...new Set(payload.relatedSymbols.map((s) => String(s).toUpperCase().trim()).filter((s) => /^[A-Z0-9]{2,15}\/USDT$/.test(s)))].slice(0, 12)
      : [],
    provenance: { trustTier: "unverified_manual", verifiedOrigin: false, untrustedContent: true },
    autoTradingEligible: false,
    createdAt: nowIso()
  };
  db.events.unshift(event);
  appendAudit(db, `手动添加日程事件:${title}（${event.due}）`, event.id, actor);
  return { ok: true, event };
}

// 未来窗口内的日程/未来事件(供 S7 透镜与事件静默判断)。
export function upcomingScheduledEvents(db, withinHours = 168) {
  const now = Date.now();
  const until = now + withinHours * 3600000;
  return (db.events || [])
    .filter((e) => {
      const t = new Date(e.due || e.startAt || 0).getTime();
      return Number.isFinite(t) && t > now && t <= until;
    })
    .sort((a, b) => new Date(a.due || a.startAt).getTime() - new Date(b.due || b.startAt).getTime());
}

// 对“已知精确时刻”的高影响事件做分阶段准备。这里只排队分析与提示，绝不直接产生交易计划：
// T-24h 更新当天上下文；T-90m 唤起一次场景/仓位复核；T+2m 唤起结果核验。
export function prepareScheduledEventMilestones(db, now = Date.now()) {
  db.system ||= {};
  db.system.eventPreparationMilestones ||= {};
  db.system.pendingNewsSignals ||= [];
  const milestones = db.system.eventPreparationMilestones;
  const reached = [];
  const wakeSignals = [];
  const events = (db.events || []).filter((event) => {
    if (!event.scheduled || Number(event.impact || 0) < 70) return false;
    const due = new Date(event.due || event.startAt || 0).getTime();
    return Number.isFinite(due) && due >= now - 10 * 60_000 && due <= now + 24 * 60 * 60_000;
  });

  for (const event of events) {
    const due = new Date(event.due || event.startAt).getTime();
    const delta = due - now;
    const stages = [];
    if (delta <= 24 * 60 * 60_000 && delta > 90 * 60_000) stages.push("T24");
    if (delta <= 90 * 60_000 && delta > 0) stages.push("T90");
    if (delta <= -2 * 60_000 && delta >= -10 * 60_000) stages.push("POST2");
    for (const stage of stages) {
      const key = `${event.id}:${stage}`;
      if (milestones[key]) continue;
      milestones[key] = nowIso();
      reached.push({ eventId: event.id, stage, title: event.title, due: event.due });
      const stageText = stage === "T24" ? "未来 24 小时事件准备" : stage === "T90" ? "事件前 90 分钟复核" : "事件结果核验";
      createNotification(db, {
        eventType: "scheduled_event_preparation", severity: stage === "T24" ? "info" : "warning",
        title: stageText, body: `${event.title} · ${event.due}。仅用于场景准备/事实复核，不预测结果，不直接触发交易。`
      });
      if (stage !== "T24") {
        wakeSignals.push({
          kind: "scheduled_event", factId: key, eventId: event.id, stage,
          symbols: event.relatedSymbols || [], impact: Number(event.impact || 80),
          publishedAt: event.due, queuedAt: nowIso(), analysisContextOnly: true, mayTriggerTradeDirectly: false,
          trustTier: event.provenance?.trustTier || (event.autoGenerated ? "verified_official_calendar" : "unverified_manual"),
          verifiedOrigin: event.provenance?.verifiedOrigin === true || event.autoGenerated === true,
          untrustedContentExcluded: true
        });
      }
    }
  }
  if (wakeSignals.length) {
    const known = new Set(db.system.pendingNewsSignals.map((item) => item.factId));
    db.system.pendingNewsSignals = [...db.system.pendingNewsSignals, ...wakeSignals.filter((item) => !known.has(item.factId))].slice(-20);
    appendAudit(db, `高影响日程进入分析复核：${wakeSignals.map((item) => item.title).join("、")}`, "scheduled_event_preparation", "ScheduledEvents", "warning");
  }
  // 仅保留最近的有限里程碑，避免常驻 system 对象无限增长。
  const entries = Object.entries(milestones).sort((a, b) => String(b[1]).localeCompare(String(a[1]))).slice(0, 300);
  db.system.eventPreparationMilestones = Object.fromEntries(entries);
  return { status: "ok", checked: events.length, reached, wakeSignals };
}
