// 日程事件(向前看):与"已发生的 RSS 新闻"(向后看)互补。带【未来 due】的已排期事件,
// 落到事件日历的未来日期 + 喂 S7 事件透镜 + 事件静默窗口。
//
// 诚实原则:只【自动生成确定性可算】的事件(规则驱动,不编造具体日期):
//   · 季度交割:季末月(3/6/9/12)的最后一个周五(多数永续/交割合约季度结算)
//   · 美国非农:每月第一个周五(NFP 固定在首个周五发布)
// FOMC / CPI / 代币解锁 等【无法可靠计算】的具体日期一律不自动编造,由用户在「添加日程事件」手动录入。
import { id, nowIso, appendAudit } from "./store.mjs";

const DAY = 86400000;

// 宏观/交割是全市场事件(非农、季度交割冲击所有主流永续)。自动生成的日程事件此前不带 relatedSymbols,
// 导致风控事件闸(需 relatedSymbols 匹配)、按标的的信息面简报与动态规则都连不上它们。这里默认标注主流币,
// 使这些市场级事件对常见授权标的真正生效。可用 MACRO_EVENT_SYMBOLS 环境变量覆盖。
const MACRO_EVENT_SYMBOLS = (process.env.MACRO_EVENT_SYMBOLS || "BTC/USDT,ETH/USDT,SOL/USDT,BNB/USDT,XRP/USDT,DOGE/USDT,ADA/USDT,SUI/USDT,LINK/USDT,AVAX/USDT")
  .split(",").map((s) => s.trim().toUpperCase()).filter(Boolean);

// 某年某月(0基)的最后一个周五(UTC)
function lastFridayUTC(year, month) {
  const d = new Date(Date.UTC(year, month + 1, 0)); // 该月最后一天
  const diff = (d.getUTCDay() - 5 + 7) % 7;          // 周五=5
  d.setUTCDate(d.getUTCDate() - diff);
  return d;
}
// 某年某月(0基)的第一个周五(UTC)
function firstFridayUTC(year, month) {
  const d = new Date(Date.UTC(year, month, 1));
  const diff = (5 - d.getUTCDay() + 7) % 7;
  d.setUTCDate(1 + diff);
  return d;
}

// 生成从 now 起未来窗口内的确定性日程事件(不落库,纯计算)。
function generateDeterministic(now = Date.now()) {
  const out = [];
  const base = new Date(now);
  const y0 = base.getUTCFullYear();
  const m0 = base.getUTCMonth();
  // 季度交割:向后 5 个季度扫季末月
  for (let q = 0; q < 6; q += 1) {
    const y = y0, m = 2 + q * 3; // Mar(2)/Jun(5)/Sep(8)/Dec(11)/next Mar...
    const yy = y + Math.floor(m / 12);
    const mm = m % 12;
    if (![2, 5, 8, 11].includes(mm)) continue;
    const d = lastFridayUTC(yy, mm);
    d.setUTCHours(8, 0, 0, 0); // 季度结算约 08:00 UTC
    if (d.getTime() > now - DAY) {
      out.push({ key: `sched_expiry_${yy}${String(mm + 1).padStart(2, "0")}`, title: `${yy}年${mm + 1}月季度合约交割`, shortTitle: "季度交割", due: d.toISOString(), category: "衍生品", impact: 55, note: "季度交割前后波动与基差收敛,注意持仓与保证金" });
    }
  }
  // 非农:未来 4 个月的首个周五
  for (let k = 0; k < 4; k += 1) {
    const y = y0 + Math.floor((m0 + k) / 12);
    const m = (m0 + k) % 12;
    const d = firstFridayUTC(y, m);
    d.setUTCHours(13, 30, 0, 0); // 美国就业数据约 13:30 UTC(时区/夏令时下为近似)
    if (d.getTime() > now - DAY) {
      out.push({ key: `sched_nfp_${y}${String(m + 1).padStart(2, "0")}`, title: `美国非农就业(NFP)· ${y}年${m + 1}月`, shortTitle: "美国非农", due: d.toISOString(), category: "宏观", impact: 75, note: "高影响宏观数据,发布前后降波动敞口(时间为近似 UTC)" });
    }
  }
  return out;
}

// 幂等落库:补齐缺失的确定性日程事件,清掉已过期>2天的自动日程(避免日历堆积)。
export function ensureScheduledEvents(db, actor = "ScheduledEvents") {
  db.events ||= [];
  const now = Date.now();
  // 清过期的自动日程
  db.events = db.events.filter((e) => !(e.scheduled && e.autoGenerated && new Date(e.due || 0).getTime() < now - 2 * DAY));
  let added = 0;
  for (const g of generateDeterministic(now)) {
    if (db.events.some((e) => e.scheduledKey === g.key)) continue;
    db.events.unshift({
      id: id("event"), scheduled: true, autoGenerated: true, scheduledKey: g.key,
      title: g.title, shortTitle: g.shortTitle, due: g.due, startAt: g.due,
      category: g.category, impact: g.impact, impactLabel: g.impact >= 70 ? "高影响" : g.impact >= 50 ? "中影响" : "低影响",
      marketWide: true, relatedSymbols: MACRO_EVENT_SYMBOLS.slice(),
      source: "日程(系统)", description: g.note, createdAt: nowIso()
    });
    added += 1;
  }
  return { added };
}

// 手动添加一条日程事件(用户录入 FOMC/CPI/解锁 等已知日期)。
export function createScheduledEvent(db, payload = {}, actor = "User") {
  db.events ||= [];
  const due = payload.due ? new Date(payload.due) : null;
  if (!due || Number.isNaN(due.getTime())) return { error: "请提供有效日期时间" };
  const title = String(payload.title || "").trim();
  if (!title) return { error: "请填写事件名称" };
  const impact = Math.max(0, Math.min(100, Number(payload.impact) || 60));
  const event = {
    id: id("event"), scheduled: true, autoGenerated: false,
    title, shortTitle: (payload.shortTitle || title).slice(0, 16),
    due: due.toISOString(), startAt: due.toISOString(),
    category: String(payload.category || "宏观").slice(0, 12),
    impact, impactLabel: impact >= 70 ? "高影响" : impact >= 50 ? "中影响" : "低影响",
    source: "日程(手动)", description: String(payload.note || "").slice(0, 200),
    relatedSymbols: Array.isArray(payload.relatedSymbols) ? payload.relatedSymbols.map((s) => String(s).toUpperCase()) : [],
    createdAt: nowIso()
  };
  db.events.unshift(event);
  appendAudit(db, `手动添加日程事件:${title}（${event.due}）`, event.id, actor);
  return { ok: true, event };
}

// 未来窗口内的日程/未来事件(供 S7 透镜与事件静默判断)。
export function upcomingScheduledEvents(db, withinHours = 168) {
  const now = Date.now();
  const until = now + withinHours * 3600000;
  return (db.events || [])
    .filter((e) => {
      const t = new Date(e.due || e.startAt || 0).getTime();
      return Number.isFinite(t) && t > now && t <= until;
    })
    .sort((a, b) => new Date(a.due || a.startAt).getTime() - new Date(b.due || b.startAt).getTime());
}
