import { useEffect, useState } from "react";
import {
  Activity, AlertTriangle, Bell, CheckCircle2, ChevronLeft, ChevronRight,
  Clock3, Database, Play, Plus, ReceiptText, RefreshCw, Search, Settings,
  ShieldCheck, Trash2
} from "lucide-react";
import { uiConfirm } from "./confirm.jsx";
import { formatDateTime, formatTime, humanize, localizeText, StatusBadge, statusTone } from "./lib.jsx";
import { t } from "./i18n.js";
import { buildOperationsView } from "./operationsView.js";

const tone = (value) => value === "critical" ? "danger" : value === "warning" ? "warning" : value === "healthy" ? "ok" : "neutral";
const severityTone = (value) => /critical|high|severe|fatal|严重|高/i.test(String(value || ""))
  ? "danger"
  : /warning|medium|moderate|警告|中/i.test(String(value || "")) ? "warning" : "neutral";
const stateLabel = (code) => ({
  action_required:t("需要处理","Action required"),degraded:t("部分降级","Degraded"),healthy:t("运行正常","Healthy"),
  paused:t("已暂停","Paused"),awaiting_first_run:t("等待首次运行","Awaiting first run"),last_run_failed:t("最近失败","Last run failed"),
  attention:t("需要关注","Needs attention"),running:t("执行中","Running"),verified:t("已校验","Verified"),broken:t("校验失败","Integrity failed"),
  configured:t("已配置","Configured"),missing:t("未配置","Not configured"),unknown:t("待确认","Unknown")
}[code]||humanize(code,t("待确认","Unknown")));

function Back({ title, onBack }) {
  return <div className="mOpsDetailNav"><button type="button" onClick={onBack}><ChevronLeft size={18}/>{t("返回","Back")}</button><b>{title}</b><span/></div>;
}

export function buildMobileTaskPayload(form = {}) {
  const isMission=form.kind==="mission";
  const name=String(form.name||form.mission||"").trim().slice(0,40);
  const schedule=String(form.schedule||"").trim();
  if(!name||!schedule||(isMission&&!String(form.mission||"").trim()))return null;
  const payload={name,type:form.type,schedule:form.type==="At"?new Date(schedule).toISOString():schedule,enabled:true,role:isMission?"intelligence":form.role,handler:isMission?"agent_mission":form.handler};
  if(isMission)payload.mission=String(form.mission).trim();
  return payload;
}

function TaskCreate({ action, onDone }) {
  const [form,setForm]=useState({name:"",kind:"standard",mission:"",type:"Every",schedule:"Every 5m",handler:"reminder",role:t("提醒","Reminder")});
  const update=(key,value)=>setForm((current)=>({...current,[key]:value}));
  const chooseType=(type)=>{const localAt=()=>{const date=new Date(Date.now()+3600000-new Date().getTimezoneOffset()*60000);return date.toISOString().slice(0,16);};setForm((current)=>({...current,type,schedule:type==="Cron"?"*/5 * * * *":type==="At"?localAt():"Every 5m"}));};
  const isMission=form.kind==="mission";
  const submit=async(event)=>{event.preventDefault();const payload=buildMobileTaskPayload(form);if(!payload)return;const result=await action("/api/tasks",payload);if(result?.id||result?.ok!==false)onDone();};
  return <div className="mOpsTaskCreate"><Back title={t("新建用户任务","New user task")} onBack={onDone}/><form onSubmit={submit}>
    <div className="mOpsTaskKind" role="tablist"><button type="button" role="tab" aria-selected={!isMission} className={!isMission?"active":""} onClick={()=>update("kind","standard")}>{t("常规任务","Standard task")}</button><button type="button" role="tab" aria-selected={isMission} className={isMission?"active":""} onClick={()=>update("kind","mission")}>{t("情报·自由任务","Intelligence mission")}</button></div>
    <label><span>{t("任务名称","Task name")}</span><input value={form.name} onChange={(event)=>update("name",event.target.value)} placeholder={isMission?t("例如：跟踪 ETH ETF 审批","Example: track ETH ETF approval"):t("例如：每日账户对账","Example: daily account reconciliation")}/></label>
    {isMission&&<label><span>{t("追踪目标（自然语言）","Objective (plain language)")}</span><textarea rows="3" value={form.mission} onChange={(event)=>update("mission",event.target.value)} placeholder={t("按计划追踪事件进展、市场影响与新证据","Track event progress, market impact, and new evidence on schedule")}/></label>}
    <label><span>{t("触发类型","Trigger type")}</span><select value={form.type} onChange={(event)=>chooseType(event.target.value)}><option>Every</option><option>Cron</option><option>At</option></select></label>
    <label><span>{form.type==="At"?t("运行时间","Run time"):t("触发表达式","Schedule expression")}</span><input type={form.type==="At"?"datetime-local":"text"} value={form.schedule} onChange={(event)=>update("schedule",event.target.value)}/></label>
    {!isMission&&<label><span>{t("执行内容","Action")}</span><select value={form.handler} onChange={(event)=>update("handler",event.target.value)}><option value="reminder">{t("通知中心提醒","Notification reminder")}</option><option value="accounting_refresh">{t("刷新账务统计","Refresh accounting")}</option><option value="reconcile">{t("执行账户对账","Reconcile account")}</option><option value="event_refresh">{t("刷新市场情报","Refresh market intelligence")}</option><option value="market_signal_refresh">{t("刷新市场信号","Refresh market signals")}</option><option value="strategy_research">{t("运行策略研究","Run strategy research")}</option><option value="paper_forward">{t("推进模拟前向","Advance paper validation")}</option><option value="trade_reflection">{t("生成平仓复盘","Generate trade reflection")}</option><option value="missed_opportunity_review">{t("复盘错过机会","Review missed opportunities")}</option></select></label>}
    <div className="mOpsFormNote"><ShieldCheck size={15}/><span>{isMission?t("Agent 按计划刷新情报并产出简报；结果进入情报中心与通知。","The Agent refreshes intelligence and publishes briefs on schedule; results appear in Intelligence and Notifications."):t("系统托管任务不能在这里创建或修改；新任务使用后端批准的真实处理器。","System-managed tasks cannot be created or edited here. New tasks use backend-approved handlers.")}</span></div><button type="submit">{isMission?t("派发情报任务","Create intelligence mission"):t("创建并加入调度器","Create and schedule")}</button>
  </form></div>;
}

function TaskDetail({ task: initial, ops, action, onBack }) {
  const task=ops.tasks.items.find((item)=>item.id===initial.id)||initial;
  const toggle=async()=>{const resume=task.enabled===false;if(await uiConfirm(resume?t(`恢复任务“${localizeText(task.name)}”？`,`Resume “${localizeText(task.name)}”?`):t(`暂停任务“${localizeText(task.name)}”？`,`Pause “${localizeText(task.name)}”?`)))action(`/api/tasks/${task.id}/${resume?"resume":"pause"}`,resume?{}:{reason:"manual_mobile"});};
  const remove=async()=>{if(await uiConfirm(t(`删除任务“${localizeText(task.name)}”？运行历史会作为审计证据保留。`,`Delete “${localizeText(task.name)}”? Run history remains as audit evidence.`))){await action(`/api/tasks/${task.id}`,{},"DELETE");onBack();}};
  return <><Back title={t("任务详情","Task detail")} onBack={onBack}/><section className={`mOpsTaskHero ${task.runtime?.tone||"neutral"}`}><small>{task.systemManaged?t("系统托管 · 定义受版本保护","System-managed · definition protected"):t("用户任务","User task")}</small><h2>{localizeText(task.name)}</h2><StatusBadge tone={tone(task.runtime?.tone)}>{stateLabel(task.runtime?.code)}</StatusBadge></section><section className="mNativeSection mOpsFacts"><div><small>ID</small><b className="mono">{task.id}</b></div><div><small>{t("处理器","Handler")}</small><b>{humanize(task.handler||task.type)}</b></div><div><small>{t("调度","Schedule")}</small><b className="mono">{task.schedule||"—"}</b></div><div><small>{t("下次运行","Next run")}</small><b>{formatDateTime(task.nextRunAt)}</b></div><div><small>{t("上次结果","Latest result")}</small><b>{humanize(task.latestRun?.status,"—")}</b></div><div><small>{t("耗时","Duration")}</small><b className="mono">{task.latestRun?.durationMs?`${task.latestRun.durationMs} ms`:"—"}</b></div></section><div className="mOpsStickyActions"><button type="button" disabled={task.enabled===false} onClick={()=>action(`/api/tasks/${task.id}/run`,{})}><Play/>{t("立即运行","Run now")}</button>{!task.systemManaged&&<button type="button" onClick={toggle}>{task.enabled===false?t("恢复","Resume"):t("暂停","Pause")}</button>}{!task.systemManaged&&<button type="button" className="danger" onClick={remove}><Trash2/>{t("删除","Delete")}</button>}</div></>;
}

function AuditDetail({ record, onBack }) {
  return <><Back title={t("审计事件","Audit event")} onBack={onBack}/><section className="mOpsAuditDetail"><StatusBadge tone={statusTone(record.status||record.severity)}>{humanize(record.status||record.severity,t("已记录","Recorded"))}</StatusBadge><h2>{localizeText(record.action)}</h2><div><span><small>ID</small><b className="mono">{record.id||"—"}</b></span><span><small>{t("时间","Time")}</small><b>{formatDateTime(record.createdAt)}</b></span><span><small>{t("操作者","Actor")}</small><b>{localizeText(record.actor||record.userName||record.role||t("系统","System"))}</b></span><span><small>{t("资源","Resource")}</small><b className="mono">{record.resource||record.target||"—"}</b></span><span><small>{t("哈希","Hash")}</small><b className="mono">{record.hash||"—"}</b></span></div><h3>{t("请求上下文","Request context")}</h3><pre>{JSON.stringify(record.context||record.payload||{},null,2)}</pre></section></>;
}

function NoticeDetail({ record, action, onBack }) {
  return <><Back title={t("通知详情","Notice detail")} onBack={onBack}/><section className="mOpsNoticeDetail"><StatusBadge tone={tone(record.tone)}>{humanize(record.severity||record.level,t("一般","Normal"))}</StatusBadge><h2>{localizeText(record.title)||t("系统通知","System notice")}</h2><p>{localizeText(record.message||record.body)||t("暂无通知内容。","No notice content.")}</p><div><span><small>ID</small><b className="mono">{record.id||"—"}</b></span><span><small>{t("来源","Source")}</small><b>{localizeText(record.source||record.category||t("系统","System"))}</b></span><span><small>{t("时间","Time")}</small><b>{formatDateTime(record.createdAt)}</b></span></div><button type="button" disabled={record.read} onClick={()=>action("/api/notifications/read",{id:record.id})}>{record.read?t("已确认","Acknowledged"):t("标记已读","Mark read")}</button></section></>;
}

export function MobileOperations({ data, action, ui, initialView="overview" }) {
  const valid=["overview","tasks","recovery","audit","notifications"];
  const [view,setView]=useState(valid.includes(initialView)?initialView:"overview");
  const [taskDetail,setTaskDetail]=useState(null),[auditDetail,setAuditDetail]=useState(null),[noticeDetail,setNoticeDetail]=useState(null),[createTask,setCreateTask]=useState(false),[query,setQuery]=useState("");
  useEffect(()=>{setView(valid.includes(initialView)?initialView:"overview");setTaskDetail(null);setAuditDetail(null);setNoticeDetail(null);},[initialView]);
  const ops=buildOperationsView(data);
  const reconcile=async()=>{if(await uiConfirm(t("立即执行账户、订单、保护与账本对账？结果会写入审计。","Run account, order, protection, and ledger reconciliation now? The result is written to audit.")))action("/api/reconciler/run",{mode:"manual_mobile"});};
  const recover=async()=>{if(await uiConfirm(t("重新启动任务调度器？现有任务定义不会被修改。","Restart the task scheduler? Existing task definitions will not be changed.")))action("/api/scheduler/recover",{});};
  if(createTask)return <div className="mOperationsNative"><TaskCreate action={action} onDone={()=>setCreateTask(false)}/></div>;
  if(taskDetail)return <div className="mOperationsNative"><TaskDetail task={taskDetail} ops={ops} action={action} onBack={()=>setTaskDetail(null)}/></div>;
  if(auditDetail)return <div className="mOperationsNative"><AuditDetail record={ops.audit.records.find((item)=>item.id===auditDetail.id)||auditDetail} onBack={()=>setAuditDetail(null)}/></div>;
  if(noticeDetail)return <div className="mOperationsNative"><NoticeDetail record={ops.notifications.items.find((item)=>item.id===noticeDetail.id)||noticeDetail} action={action} onBack={()=>setNoticeDetail(null)}/></div>;
  const auditRows=ops.audit.records.filter((row)=>!query||[row.action,row.actor,row.resource,row.target,row.id].some((value)=>String(value||"").toLowerCase().includes(query.toLowerCase())));
  return <div className="mOperationsNative"><div className="mOpsRail" role="tablist">{[["overview",t("值班台","Command")],["tasks",t("任务","Tasks")],["recovery",t("恢复","Recovery")],["audit",t("审计","Audit")],["notifications",t("通知","Inbox")]].map(([id,label])=><button type="button" role="tab" aria-selected={view===id} className={view===id?"active":""} key={id} onClick={()=>setView(id)}>{label}{id==="notifications"&&ops.notifications.unread?<i>{ops.notifications.unread}</i>:null}</button>)}</div>
    {view==="overview"&&<Overview ops={ops} ui={ui}/>} 
    {view==="tasks"&&<Tasks ops={ops} onCreate={()=>setCreateTask(true)} onSelect={setTaskDetail}/>} 
    {view==="recovery"&&<Recovery ops={ops} action={action} ui={ui} reconcile={reconcile} recover={recover}/>} 
    {view==="audit"&&<Audit ops={ops} rows={auditRows} query={query} setQuery={setQuery} ui={ui} onSelect={setAuditDetail}/>} 
    {view==="notifications"&&<Inbox ops={ops} action={action} ui={ui} onSelect={setNoticeDetail}/>} 
  </div>;
}

function Overview({ ops, ui }) {
  return <><section className={`mOpsStatus ${ops.overall.tone}`}><div><span>{ops.overall.tone==="healthy"?<CheckCircle2/>:<AlertTriangle/>}</span><div><small>{t("当前运行状态","Current runtime")}</small><h2>{stateLabel(ops.overall.label)}</h2></div><StatusBadge tone={tone(ops.overall.tone)}>{ops.overall.openAttention} {t("项待处理","open")}</StatusBadge></div><p>{ops.overall.tone==="healthy"?t("关键运行链路未发现阻断。","No blocker is visible across the critical runtime path."):t("最后有效事实继续保留；请按下方优先级处理异常。","Last-valid facts remain visible; resolve exceptions in the priority order below.")}</p><footer><span><small>{t("任务","Tasks")}</small><b>{ops.tasks.active}/{ops.tasks.total}</b></span><span><small>{t("输入","Inputs")}</small><b>{ops.inputs.enabled}/{ops.inputs.total}</b></span><span><small>{t("异常服务","Critical")}</small><b>{ops.overall.criticalServices}</b></span></footer></section><section className="mNativeSection mOpsServices"><header><div><b>{t("运行健康","Runtime health")}</b><small>{t("点击进入权威上下文","Open authoritative context")}</small></div></header>{ops.services.map((item)=><button type="button" key={item.id} onClick={()=>ui.setActive(item.route)}><span className={item.tone}/><div><b>{t(item.labelZh,item.labelEn)}</b><small>{item.detail?localizeText(item.detail):humanize(item.value)}</small></div><StatusBadge tone={tone(item.tone)}>{humanize(item.value,t("待确认","Unknown"))}</StatusBadge><ChevronRight/></button>)}</section><section className="mNativeSection mOpsAttention"><header><div><b>{t("待处理队列","Attention queue")}</b><small>{t("按恢复优先级排序","Ordered by recovery priority")}</small></div><span>{ops.attention.length}</span></header>{ops.attention.slice(0,7).map((item,index)=><button type="button" key={`${item.kind}-${item.id}-${index}`} onClick={()=>ui.setActive(item.route)}><i className={item.tone}>{index+1}</i><div><b>{t(item.titleZh,item.titleEn)}</b><small>{localizeText(item.detail)||formatDateTime(item.createdAt)}</small></div><ChevronRight/></button>)}{!ops.attention.length&&<div className="mNativeEmpty compact"><CheckCircle2/><b>{t("队列已清空","Queue is clear")}</b></div>}</section><section className="mNativeSection mOpsInputs"><header><div><b>{t("事件输入健康","Event input health")}</b><small>{t("日历仍在 AI 交易员中显示","Calendar remains in AI Trader")}</small></div><button type="button" onClick={()=>ui.setActive("eventsTasks:events")}>{t("日历","Calendar")}</button></header>{ops.inputs.items.slice(0,6).map((item)=><div key={item.id}><span className={item.tone}/><div><b>{localizeText(item.name)}</b><small>{item.error?localizeText(item.error):formatDateTime(item.checkedAt||item.lastSuccessAt)}</small></div><StatusBadge tone={tone(item.tone)}>{item.enabled?humanize(item.status):t("已停用","Disabled")}</StatusBadge></div>)}</section></>;
}

function Tasks({ ops, onCreate, onSelect }) {
  return <><section className="mOpsListHead"><div><h2>{t("任务与真实运行","Tasks and actual runs")}</h2><p>{t("定义归属与运行结果分开显示。","Definition ownership and runtime outcome are separate.")}</p></div><button type="button" onClick={onCreate}><Plus/>{t("新建","New")}</button></section><div className="mOpsTaskStats"><span><small>{t("运行中","Active")}</small><b>{ops.tasks.active}</b></span><span><small>{t("失败","Failed")}</small><b>{ops.tasks.failedRuns}</b></span><span><small>{t("成功率","Success")}</small><b>{ops.tasks.successPct==null?"—":`${ops.tasks.successPct.toFixed(0)}%`}</b></span></div><section className="mNativeSection mOpsTaskList">{ops.tasks.items.map((task)=><button type="button" key={task.id} onClick={()=>onSelect(task)}><span className={task.runtime.tone}/><div><b>{localizeText(task.name)}</b><small>{task.systemManaged?t("系统托管","System-managed"):t("用户任务","User task")} · {task.schedule||"—"}</small><em>{formatDateTime(task.latestRun?.finishedAt||task.latestRun?.createdAt||task.lastRunAt)}</em></div><StatusBadge tone={tone(task.runtime.tone)}>{stateLabel(task.runtime.code)}</StatusBadge><ChevronRight/></button>)}{!ops.tasks.items.length&&<div className="mNativeEmpty"><Clock3/><b>{t("暂无任务","No tasks")}</b></div>}</section><section className="mNativeSection mOpsRunList"><header><div><b>{t("最近运行","Recent runs")}</b><small>{ops.tasks.recentRuns.length} {t("条证据","records")}</small></div></header>{ops.tasks.recentRuns.slice(0,10).map((run)=><div key={run.id}><time>{formatTime(run.finishedAt||run.createdAt)}</time><span><b>{localizeText(run.taskName||run.name||run.handler)}</b><small>{run.durationMs?`${run.durationMs} ms`:String(run.id||"").slice(0,12)}</small></span><StatusBadge tone={statusTone(run.status)}>{humanize(run.status)}</StatusBadge></div>)}</section></>;
}

function Recovery({ ops, action, ui, reconcile, recover }) {
  return <><section className={`mOpsRecoveryTruth ${ops.recovery.healthy?"healthy":"warning"}`}><div><RefreshCw/><span><small>{t("最近对账","Latest reconciliation")}</small><h2>{ops.recovery.healthy?t("账实一致","Consistent"):ops.recovery.latestReconciliation?t("仍有差异","Differences remain"):t("尚无证据","No evidence yet")}</h2><p>{formatDateTime(ops.recovery.latestReconciliation?.createdAt)}</p></span></div><button type="button" onClick={reconcile}>{t("立即对账","Run now")}</button></section><section className="mNativeSection mOpsDifferences"><header><div><b>{t("差异清单","Difference ledger")}</b><small>{t("以后端报告为准","Backend report is authoritative")}</small></div><span>{ops.recovery.differences.length}</span></header>{ops.recovery.differences.map((item,index)=><div key={item.id||index}><span className={severityTone(item.severity)}/><div><b>{localizeText(item.title||item.message||item.kind||item.field)||t("未命名差异","Unnamed difference")}</b><small>{localizeText(item.detail||item.reason)||[item.local,item.exchange].filter((value)=>value!=null).join(" → ")}</small></div></div>)}{!ops.recovery.differences.length&&<div className="mNativeEmpty compact"><CheckCircle2/><b>{t("没有已报告差异","No reported differences")}</b></div>}</section><section className="mNativeSection mOpsRecoveryActions"><header><div><b>{t("安全恢复动作","Safe recovery actions")}</b><small>{t("不模拟成功，等待后端新事实","No simulated success; wait for backend truth")}</small></div></header><button type="button" onClick={reconcile}><RefreshCw/><span><b>{t("重新执行对账","Re-run reconciliation")}</b><small>{t("账户、订单、保护与账本","Account, orders, protection, ledger")}</small></span><ChevronRight/></button><button type="button" disabled={!ops.recovery.needsSchedulerRecovery} onClick={recover}><Activity/><span><b>{t("恢复任务调度器","Recover task scheduler")}</b><small>{ops.recovery.needsSchedulerRecovery?t("检测到失败或重试","Failure or retry detected"):t("当前无恢复信号","No recovery signal")}</small></span><ChevronRight/></button><button type="button" onClick={()=>ui.setActive("tradeJournal")}><ReceiptText/><span><b>{t("执行恢复","Execution recovery")}</b><small>{ops.recovery.unknownOrders.length} {t("笔待权威结果","awaiting authoritative outcome")}</small></span><ChevronRight/></button></section><section className="mNativeSection mOpsIncidents"><header><div><b>{t("未处理风险事件","Open risk incidents")}</b><small>{t("处理后仍由后端复算运行状态","Backend recalculates runtime after review")}</small></div><span>{ops.recovery.openIncidents.length}</span></header>{ops.recovery.openIncidents.map((item)=><div key={item.id}><span className={severityTone(item.severity)}/><div><b>{localizeText(item.title)}</b><small>{formatDateTime(item.createdAt)}</small></div><button type="button" onClick={async()=>{if(await uiConfirm(t("确认该事件已完成核查？","Confirm this incident has been reviewed?")))action(`/api/risk/incidents/${item.id}/close`,{});}}>{t("处理","Resolve")}</button></div>)}</section></>;
}

function Audit({ ops, rows, query, setQuery, ui, onSelect }) {
  return <><section className="mOpsAuditProof"><div className={ops.audit.chain}><ShieldCheck/><span><small>{t("审计链","Audit chain")}</small><b>{stateLabel(ops.audit.chain)}</b></span></div><div className={ops.audit.worm}><Database/><span><small>WORM</small><b>{stateLabel(ops.audit.worm)}</b></span></div></section><div className="mOpsAuditTools"><label><Search/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={t("搜索审计记录","Search audit records")}/></label><button type="button" onClick={()=>ui.download?.("/api/audit-logs/export?format=json","kordyn-audit.json")}>{t("导出","Export")}</button></div><section className="mNativeSection mOpsAuditList">{rows.map((row)=><button type="button" key={row.id} onClick={()=>onSelect(row)}><time>{formatDateTime(row.createdAt)}</time><div><b>{localizeText(row.action)}</b><small>{localizeText(row.actor||row.role||t("系统","System"))} · {row.resource||row.target||"—"}</small></div><StatusBadge tone={statusTone(row.status||row.severity)}>{humanize(row.status||row.severity,t("已记录","Recorded"))}</StatusBadge><ChevronRight/></button>)}{!rows.length&&<div className="mNativeEmpty"><Search/><b>{t("没有匹配记录","No matching records")}</b></div>}</section></>;
}

function Inbox({ ops, action, ui, onSelect }) {
  return <><section className="mOpsListHead"><div><h2>{ops.notifications.unread?t(`${ops.notifications.unread} 条等待确认`,`${ops.notifications.unread} await acknowledgement`):t("通知队列已处理","Notification queue is clear")}</h2><p>{t("通知不是交易事实；委托与持仓仍以 Live Desk 为准。","Notices are not trading truth; Live Desk remains authoritative.")}</p></div><button type="button" disabled={!ops.notifications.unread} onClick={()=>action("/api/notifications/read",{})}>{t("全部已读","Read all")}</button></section><section className="mNativeSection mOpsNoticeList">{ops.notifications.items.map((item)=><button type="button" className={item.read?"read":"unread"} key={item.id} onClick={()=>onSelect(item)}><span className={item.tone}/><div><b>{localizeText(item.title)||t("系统通知","System notice")}</b><p>{localizeText(item.message||item.body)||"—"}</p><small>{formatDateTime(item.createdAt)} · {localizeText(item.source||item.category||t("系统","System"))}</small></div><StatusBadge tone={tone(item.tone)}>{humanize(item.severity||item.level,t("一般","Normal"))}</StatusBadge><ChevronRight/></button>)}{!ops.notifications.items.length&&<div className="mNativeEmpty"><Bell/><b>{t("暂无通知","No notices")}</b></div>}</section><button type="button" className="mOpsConfigLink" onClick={()=>ui.setActive("systemSettings:notifications")}><Settings/><span><b>{t("配置投递渠道","Configure delivery channels")}</b><small>{t("飞书、Telegram 与告警 Webhook","Lark, Telegram, and alert webhook")}</small></span><ChevronRight/></button></>;
}
